# Generated by Django 4.1.2 on 2022-12-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('body_comment', models.CharField(max_length=7000)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('body', models.CharField(max_length=15000)),
                ('tags', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('comments', models.IntegerField()),
            ],
        ),
    ]
