# Generated by Django 4.1.2 on 2022-12-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='post_id',
            field=models.IntegerField(null=True),
        ),
    ]
