# Generated by Django 4.1.2 on 2022-12-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='body_comment',
            field=models.CharField(blank=True, max_length=7000),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='comments',
            field=models.IntegerField(null=True),
        ),
    ]
