# Generated by Django 4.1.2 on 2022-12-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_remove_post_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='body_comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comments',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
